### ISSUE TITLE
Ambiguous column name error

### ISSUE THREAD

**Issue by patrickhartling** [project-imas/encrypted-core-data#103]
I am trying to use the latest Encrypted Core Data source (f7db860ac50117a444a48c0acc70b994a88c9d31), and I have an issue where SQLite reports an ambiguous column name. The statement being executed is the following:

```
SELECT DISTINCT ecdTransaction.__objectID FROM ecdTransaction
LEFT OUTER JOIN ecdAccount AS [account] ON ecdTransaction.account__objectid = [account].__objectID
LEFT OUTER JOIN ecdAccount AS [account] ON ecdTransaction.account__objectid = [account].__objectID
LEFT OUTER JOIN ecdUser AS [account.user] ON [account].user__objectid = [account.user].__objectID
LEFT OUTER JOIN ecdAccount AS [account] ON ecdTransaction.account__objectid = [account].__objectID
WHERE ([account].hidden = ? AND [account].__objectID = ? AND [account].accountType != ? AND ecdTransaction.active = ?)
ORDER BY ecdTransaction.dateHolder  DESC, ecdTransaction.insertionIndex  ASC;
```

The error is for `account.hidden`. The source for the `NSPredicate` that was used in the fetch request is as follows:

```objc
NSArray *const predicates =
    @[[NSPredicate predicateWithFormat:@"account.hidden == NO"],
      [NSPredicate predicateWithFormat:@"account.user == %@", activeUser],
      [NSPredicate predicateWithFormat:@"account.accountType != %d", kExcludedAccountType],
      [NSPredicate predicateWithFormat:@"active == YES"],
      ];
NSPredicate *const compoundPredicate =
    [NSCompoundPredicate andPredicateWithSubpredicates:predicates];
```

If I remove the `account.user == ...` subpredicate, then the SQLite error is resolved. However, that is not strictly the correct predicate for our purposes.

**Comment by Bdar1** [comment]
Hey, I am getting same issue in latest build, did anyone fix that?

**Comment by jonathanrfisher** [comment]
Are we sure it is not actually a problem with accessing values of a relationship in a predicate?  I had this problem with ECD.  I am able to fetch a set of related objects, but I'm not able to filter that set within the predicate if that makes sense.

For example:

I might have an NSManagedObject named Contact which might have a relationship with another NMO called Phone.

I can GET the set of phones via fetchrequest with a predicate but I CANNOT get a specific phone with some given number.

I think you understand, but say I have 100 contacts and 30 of them have at least 1 phone number with an area code of 770.  I have not (in the past at least) been able to write a predicate with ECD that fetches only those contacts that have the 770 area code.  I had to get the entire set and filter the array with a predicate, which is terrible...

**Comment by aksswami** [comment]
I am also getting the same error while performing complex query.
```
NSPredicate *predicate = [NSPredicate predicateWithFormat:@"(%K == %@ AND  ((ANY parentKey.key == %@ AND ANY parentKey.value == %@)))",CDDropDownsAttributes.entityID, entityID, firstKey, firstValue];
```

Any Solution?
