### ISSUE TITLE
Light migration seems to throw incorrect passcode error?

### ISSUE THREAD

**Issue by jasper-ch-chan** [project-imas/encrypted-core-data#133]
I was wondering if anyone has had success performing a light migration using ECD? I've been assertion failures due to incorrect passcode. However, I assure you the passcode is the same before and after attempting the light migration.

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unable to add persistent store
Error Domain=EncryptedStoreErrorDomain Code=6000 "Incorrect passcode" UserInfo=0x7e2813d0 {NSUnderlyingError=0x7e2793f0 "The operation couldn’t be completed. (NSSQLiteErrorDomain error 26.)", NSLocalizedDescription=Incorrect passcode}'

**Comment by Hema1Latha** [comment]
i'm also facing the same issue Unresolved error in establishing core data stack Error Domain=EncryptedStoreErrorDomain Code=6000 "Incorrect passcode" UserInfo={NSLocalizedDescription=Incorrect passcode, NSUnderlyingError=0x280ecfcc0 {Error Domain=NSSQLiteErrorDomain Code=26 "(null)" UserInfo={EncryptedStoreErrorMessage=file is not a database}}}

How to resolve this issue
