### ISSUE TITLE
Error in fetch objectid

### ISSUE THREAD

**Issue by simplydesigner** [project-imas/encrypted-core-data#143]
NSFetchRequest *request = [Record MR_requestAllSortedBy:@"timeCreated" ascending:YES inContext: localContext];
NSExpressionDescription* objectIdDesc = [NSExpressionDescription new];
objectIdDesc.name = @"Record";
objectIdDesc.expression = [NSExpression expressionForKeyPath:@"objectID"];
objectIdDesc.expressionResultType = NSObjectIDAttributeType;
    
[request setPropertiesToFetch:@[@"size", objectIdDesc]];
[request setResultType: NSDictionaryResultType];
    
NSArray * records = [Record MR_executeFetchRequest: request];

#### error  in entity not by nil

-(id)expressionDescriptionTypeValue:(NSExpressionDescription *)expressionDescription
                withReferenceNumber:(NSNumber *)number {
    
    switch ([expressionDescription expressionResultType]) {
        case NSObjectIDAttributeType:
            return [self newObjectIDForEntity:[expressionDescription entity] referenceObject:number];
            break;

#####replace to

-(id)expressionDescriptionTypeValue:(NSExpressionDescription *)expressionDescription
                withReferenceNumber:(NSNumber *)number {
    
    switch ([expressionDescription expressionResultType]) {
        case NSObjectIDAttributeType: {
            
            NSEntityDescription * entityDescription = self.persistentStoreCoordinator.managedObjectModel.entitiesByName[expressionDescription.name];
            
            return [self newObjectIDForEntity: entityDescription referenceObject:number];
        }
        break;
            
            /*  NSUndefinedAttributeType
             *  NSInteger16AttributeType
             *  NSInteger32AttributeType
             *  NSInteger64AttributeType
             *  NSDecimalAttributeType
             *  NSDoubleAttributeType
             *  NSFloatAttributeType
             *  NSStringAttributeType
             *  NSBooleanAttributeType
             *  NSDateAttributeType
             *  NSBinaryDataAttributeType
             *  NSTransformableAttributeType
             */
            
        default:
            return nil;
            break;
    }
}

**Comment by zerpt** [comment]
@simplydesigner 
Your fix breaks the use of setting the entity in the expression description object. I made and pushed a fix that allows using either or.
