### ISSUE TITLE
Can't open SQLite file

### ISSUE THREAD

**Issue by farisolusa** [project-imas/encrypted-core-data#144]
I'm trying to open the SQLite file in finder using SQLite Database browser but it asks for the password which I am putting that I set in EncryptedStorePassphraseKey but it is not accepting it. Am I doing something wrong? Please advice!

**Comment by zerpt** [comment]
@farisolusa 
The normal SQLite tool won't work with the encrypted sqlite files. You'll need to get the SQLCipher utility to decrypt the database.
