### ISSUE TITLE
CoreData could not fulfill a fault for...

### ISSUE THREAD

**Issue by Magnat12** [project-imas/encrypted-core-data#145]
When I use persistent store coordinator with SQLCipher, it always crash with fault one-to-many relationship after first app relaunch. So when I first time launch the app, I create NSManagedObjects with relationships, then, when I save db, and reopen the app, it crash when I try to access to these relationship. Without SQLCipher everything works fine.

Here is the code for SQLCipher persistent store initialize:
```
- (NSPersistentStoreCoordinator *)persistentStoreCoordinator
{
    if (!_persistentStoreCoordinator) {
        NSURL *storeURL = [[self applicationDocumentsDirectory] URLByAppendingPathComponent:@"MyApp.sqlite"];
        NSDictionary *options = @{EncryptedStorePassphraseKey: @"MyApp",
                                                            EncryptedStoreDatabaseLocation: storeURL};
        NSError *error;
        _persistentStoreCoordinator = [EncryptedStore makeStoreWithOptions:options managedObjectModel:[self managedObjectModel] error:&error];
        if (error) {
            NSLog(@"%@", error);
        }
    }

    return _persistentStoreCoordinator;
}
```

**Comment by Magnat12** [comment]
Issue was that one of my property for NSManagedObject has name "index", but I found, that this name used EncryptedStore internally, to store information

**Comment by sigmundfridge** [comment]
Are there any other terms used internally? I receive a similar crash for an NSManagedObject with a property 'status' and was wondering if that is the issue....

**Comment by Magnat12** [comment]
Maybe it is related. Just try to remove your property from `status` to something different and you will see. If crash still happens, problem is somewhere else.
