### ISSUE TITLE
Unable to add persistent store null

### ISSUE THREAD

**Issue by devKrishnan** [project-imas/encrypted-core-data#146]
I get this problem when I added a new class and made few changes to relationship among classes.

I could not resolve it at all.

The options dictionary I pass is below

optionsForSqlCipher = @{NSMigratePersistentStoresAutomaticallyOption:[NSNumber numberWithBool:YES],NSInferMappingModelAutomaticallyOption: [NSNumber numberWithBool:YES], EncryptedStorePassphraseKey: SampleValue,
                                EncryptedStoreDatabaseLocation: [storeURL absoluteString]
                                };

should I add any more parameters to the options dictionary.

**Comment by zerpt** [comment]
@devKrishnan 
Would you be able to post the full exception text? ECD is lacking some support for model change migrations, so this could be your trouble, but the exception text should shed more light.
