### ISSUE TITLE
NSPredicate searching not working with cyrillic characters

### ISSUE THREAD

**Issue by K1rix** [project-imas/encrypted-core-data#148]
NSPredicate *pred = [[NSPredicate alloc] init];
pred = [NSPredicate predicateWithFormat:@"name CONTAINS[c] %@", searchString];
[fetchRequest setPredicate:pred];
NSArray *array = [context executeFetchRequest:fetchRequest error:nil];

It works perfectly with latin characters, but when I use cyrillic it returns 0 objects

**Comment by D-Wang** [comment]
@K1rix Hi, have you found any resolution for this problem?

**Comment by zerpt** [comment]
@K1rix 
Hmm, I think it would work if ECD would just encode all strings to UTF8 on searching and inserting, and decoding when fetching. I'm not sure how soon I'll be able to try this out, but that would probably solve your issue.

**Comment by K1rix** [comment]
@zerpt 
I'll try this. But could you explain in general where i need make changes?

**Comment by byzyn4ik** [comment]
I tried Russian an Ukrainian (Cyrillic languages) and also has found a bug. Also doesn't allowing any diacritic symbols for Polish , Czech.

**Comment by K1rix** [comment]
Do ECD and sqlcipher use utf-8 encoding by default? I've looked over the code of the libraries. ECD does [obj UTF8String] before sqlite3_bind_text, which uses utf8 for database by default.

**Comment by K1rix** [comment]
And there's no reason to encode when inserting, because all strings are corrected after fetching with the predicate, which contains number.

**Comment by byzyn4ik** [comment]
Why this is not marked as a bug? Does anyoune have the solution?

**Comment by K1rix** [comment]
@artyomkiss thanx, it works!
