### ISSUE TITLE
NSString comparsion operators -- CONTAINS/LIKE -- it doesn't work on NSData.

### ISSUE THREAD

**Issue by hisavali** [project-imas/encrypted-core-data#152]
**Problem**: 
Once encrypted values are stored as NSData in persistent store, if fetch takes place with NSPredicate which uses string (not basic) comparisons operators -- CONTAINS/LIKE -- it doesn't work for NSData.
 
Note: I have to stop having random values for 'iv' & 'salt' generated in DataGenerator.m
Please find my code chances in gist listed below. I have provided comments against working & non-working code.
 
**Question:** In order to fetch data, how to form sql query (predicate) with string operators 'like, contains or match' for encrypted data.

Please find more information here:
https://gist.github.com/hisavali/b15a4a8e875c73458d80

**Comment by D-Wang** [comment]
@hisavali  Hi, have found any solution for this?

**Comment by hisavali** [comment]
@D-Wang I have NOT. Actual problem is when NSData tries to use NSString operators like 'Contains', 'like', 'match', etc.

Original code with following predicate works:

    [fetchRequest setPredicate:[NSPredicate predicateWithFormat:@"%K == %@", @"encrypted_field", value]];

It works because NSData object can use basic operator like ==, !=, etc.

**Comment by zerpt** [comment]
@hisavali 
1) I'm having trouble reproducing your issue with NSPredicates. I followed your gist code and made the following test base code:
```objc
NSManagedObject* obj = [NSEntityDescription insertNewObjectForEntityForName:@"User" inManagedObjectContext:context];
NSString *value = @"myName";
[obj setValue:value forKeyPath:@"name"];
[context save:nil];
    
NSFetchRequest *req = [[NSFetchRequest alloc] init];
[req setEntity:[NSEntityDescription entityForName:@"User" inManagedObjectContext:context]];
[req setPredicate:[NSPredicate predicateWithFormat:@"%K LIKE %@", @"name", value]];
NSArray *array = [context executeFetchRequest:req error:nil];
for (NSManagedObject* o in array) {
    NSLog(@"\n%@", o);
    [context deleteObject:o];
}
[context save:nil];
```

I've tried `==` and `LIKE` and `CONTAINS` in the predicate format definition, and they all seem to work. Maybe I've missed an important detail in your Gist? Please advise.

2) I'm not sure I understand why you need the salt and IV removed, but more importantly, ECD alone doesn't do any actual encryption work. ECD acts as the translation between the usual Core Data hooks and an underlying SQLCipher library, which is what executes SQL statements and performs all encryption/decryption. Your Gist refers to a `DataGenerator.m` file and a
```objc
+ (NSData *)createRandomDataOfLength:(size_t)length
```
method that ECD doesn't implement, so I'm not sure I will be able to help with this issue.

**Comment by hisavali** [comment]
@zerpt : Thank you for your time. I just realised that I have created this issue on wrong repository. 

My gist is an extract of an example code listed here: https://github.com/DavidBenko/Encrypted-Core-Data.git (Please notice name 'Encrypted-Core-Data'; I got confused with project-imas ECD)

It uses NSValueTransformer to do encryption of an individual attribute. While encryption it does use IV & Salt.

I'll close this issue.

Thanks again.
