### ISSUE TITLE
Is this working with the iOS 8.1 SDK?

### ISSUE THREAD

**Issue by ob1techno** [project-imas/encrypted-core-data#153]
Hello,

I know your readme only specifies support for iOS 6.0-7.1, but I wondered if you have any experience with 8.1.

I'm using this in a project which works fine compiled against the 7.1 SDK, but is crashing with various exceptions when compiled against the 8.1 SDK.

Thanks,

Olly

**Comment by jasper-ch-chan** [comment]
I am currently using 8.1 SDK and it works fine for me... no crashes

**Comment by ob1techno** [comment]
OK thanks Japser - I will explore other reasons for the crashes - just wanted to rule this out.
