### ISSUE TITLE
No support for ordered relationships

### ISSUE THREAD

**Issue by dehydr8** [project-imas/encrypted-core-data#157]
It looks like the library doesn't support ordered relationships. CoreData changes a to-many relationship from NSSet to NSOrderedSet to maintain the ordering of the elements. It also supports the inverse relationship arrangement.

Is this feature planned?

**Comment by gavin-black** [comment]
Fixed by #158, thanks again @dehydr8

**Comment by coffellas-cto** [comment]
Just got this bug when using NSOrderedSet for to-many relationship. The sorting doesn't survive my app's restart.

**Comment by aleufms** [comment]
I have to add ".__objectid" on relationship parameters. Otherwise, the lib doesn't know that patient is an a relationship column. Example:

>     self.prescriptions = [Prescription MR_fetchAllGroupedBy:@"patient" withPredicate:predicate sortedBy:@"patient.__objectid,date" ascending:NO];
