### ISSUE TITLE
Auto-migration causes crash

### ISSUE THREAD

**Issue by sigmundfridge** [project-imas/encrypted-core-data#160]
Can I confirm that auto-migration isn't currently supported?

**Comment by sdwornik** [comment]
To this date, I don't think anyone has gotten migration to work with ECD.

**Comment by gavin-black** [comment]
Our team did not add in this ability when originally building ECD.  It should be possible, but definitely not a trivial update.

**Comment by jasper-ch-chan** [comment]
@sigmundfridge You should pull from the master repo as the master repo recently pulled in my bug fixes for lightweight auto migration.

**Comment by jasper-ch-chan** [comment]
@sigmundfridge Have you tried pulling in the latest master repo and retesting your auto migration? If it solves your problem, please close this issue.

**Comment by sigmundfridge** [comment]
Unfortunately I cannot test this as the most recent master triggers a crash (without automigration). I haven't had chance to investigate that  (or open a bug report). I will close this issue now, but reopen if I find problems later.

**Comment by jasper-ch-chan** [comment]
@sigmundfridge Okay please keep me in the loop about this as I spent a lot of time on the lightweight auto migration code and I'm pretty friendly with it. If there are problems, I would be happy to help resolve them.
