### ISSUE TITLE
Crash in line 1764 if the object doesn't have inverse relationship

### ISSUE THREAD

**Issue by sahara108** [project-imas/encrypted-core-data#169]
Hi, my db doesn't have inverse relationship, so that the library is alway crashed in line 1764 
                    `NSSet* values = [relationshipObject valueForKey:[inverse name]];
                    if ([values isKindOfClass:[NSOrderedSet class]]) {
                        NSOrderedSet* orderedValues = (NSOrderedSet*) values;
                        orderSequence = @([orderedValues indexOfObject:object]);
                    }`

I have added a quick fix:

`if (inverse) {
                        NSSet* values = [relationshipObject valueForKey:[inverse name]];
                        if ([values isKindOfClass:[NSOrderedSet class]]) {
                            NSOrderedSet* orderedValues = (NSOrderedSet*) values;
                            orderSequence = @([orderedValues indexOfObject:object]);
                        }
                    }`

But I see that there are many lines doesn't check for the inverse relationship, it may cause another crash in future.

**Comment by dorada** [comment]
Inverse relationships are core data best practice and are required at this time.

encrypted-core-data will now throw an assert if one does not exist
