### ISSUE TITLE
Unable to add persistent store Error Domain=NSSQLiteErrorDomain Code=5 "The operation couldn’t be completed

### ISSUE THREAD

**Issue by irshadpc** [project-imas/encrypted-core-data#172]
CoreData: error: -addPersistentStoreWithType:EncryptedStore configuration:(null) URL:file:///var/mobile/Containers/Data/Application/46A66B66-52DC-47EB-9A2F-374FC6E59DF1/Documents/mPassbook.sqlite options:{
    EncryptedStorePassphrase = "6e44DbH9qHSPuhTv7s/sKw==";
} ... returned error Error Domain=NSSQLiteErrorDomain Code=5 "The operation couldn’t be completed. (NSSQLiteErrorDomain error 5.)" UserInfo=0x534d00 {EncryptedStoreErrorMessage=database is locked} with userInfo dictionary {
    EncryptedStoreErrorMessage = "database is locked";
}
Assertion failure in +[EncryptedStore makeStoreWithOptions:managedObjectModel:], /Users/irshadpc/Documents/ios/encrypted-core-data/Incremental Store/EncryptedStore.m

the above error i got consistently got it.Any one please help me..

**Comment by zhuxi1989** [comment]
I met something similar. It says passcode incorrect while Im sure it's correct... Internally, the error is SQLITE_BUSY. Im still investigating it.  Here someone explain why SQLITE_BUSY happen :http://stackoverflow.com/questions/8559623/sqlite-busy-the-database-file-is-locked-database-is-locked-in-wicket

**Comment by dorada** [comment]
Is this still an issue?

**Comment by irshadpc** [comment]
@dorada . Yes, i have expirenced same issue with me.

**Comment by dorada** [comment]
I'll leave this here then, but until we have a repeatable test case won't take any action.

**Comment by irshadpc** [comment]
@DanielBroad Ok,Will report.

**Comment by tomasz-czyzak** [comment]
I have this issue from time to time...
In my scenario save on context is called when re-encryption (sqlite_rekey) is in progress.
So I was wondering if calling:
    [self.database.managedObjectContext performBlockAndWait:^{
        [... changeDatabasePassphrase:newPasscode error:&error];
    }];
will be safe...
