### ISSUE TITLE
Upgrade from 2.0 to 3.0 causes fatal crash

### ISSUE THREAD

**Issue by sigmundfridge** [project-imas/encrypted-core-data#173]
I decided to update from 2.0 to 3.0. I have made some changes to 2.0 (such as #154) but they were quick fixes I didn't mind temporarily losing (and shouldn't affect the main scope of my code). 
However, I seem to have a problem saving one particular NSManagedObject. I consistently got a crash (NSObjectInaccessibleException', reason: 'CoreData could not fulfill a fault ...) whenever I tried to use that NSManagedObject.  As a test I removed all relationships and strangely got a new error -  Magical Records freezing at 
'MagicalRecord Root Saving Context' is about to save: obtaining permanent IDs for XX new inserted object(s).'

This is going to be a horribly difficult vague bug to solve, so I was wondering if anyone else has experienced similar since release 3.0?

**Comment by lutzmi** [comment]
Hi,

were you able to track down the issue? I am currently experiencing the same "CoreDate could not fulfill a fault" issue...

Thanks, Michael

**Comment by sigmundfridge** [comment]
Not yet. Do you know what nsmanagedobject is causing the issue? I suspect a property on one of mine is conflicting with an encrypted store property. The nsmo that crashes for me has a property 'status' that would be my prime candidate.

On 21 Jun 2015 11:52, lutzmi <notifications@github.com> wrote:
Hi,

were you able to track down the issue? I am currently experiencing the same "CoreDate could not fulfill a fault" issue...

Thanks, Michael

---

**Comment by lutzmi** [comment]
I know the namanagedobject. Do you know a way to know what properties the encrypted store uses?
(Don't have one named "status" ;-).

**Comment by lutzmi** [comment]
The entities/nsmanagedobjects that caused the issue had a parent entity. I removed that and now it seems to work. Need to do more testing, though. See also issue #151.

**Comment by sigmundfridge** [comment]
Hmmmmm. All of my NSMOs have parent entities. They all seem to be saved OK, until the final one (with the 'status' property.
My hunch was based on this (now closed) issue #145.
I was going to go through the model, removing properties one by one to see if I could pinpoint a conflicting property. 

For #145 the issue appears to be an 'index' property.

**Comment by jasper-ch-chan** [comment]
@sigmundfridge To answer your question about special keywords reserved by SQLite (http://www.sqlite.org/lang_keywords.html) - IE. you should not use them as your attribute name

**Comment by lutzmi** [comment]
Thanks. Then it was not an issue with keywords in my case. So it's probably more than one cause for this issue.

**Comment by icecoffin** [comment]
I'm also experiencing the same issue ("CoreData could not fulfill a fault"), with one entity only. Didn't find any reserved names in my entity attributes or relationships.
My entity also has two one-to-many relationships with one another entity. Can this be the reason?

**Comment by jasper-ch-chan** [comment]
@icecoffin I find that very unlikely as I have multiple relationships between entities of various types (One-to-one, one-to-many and many-to-many) and they all work fine.

**Comment by icecoffin** [comment]
@jasper-ch-chan I mean that I have two relationships with the same entity. 
In particular, I have a Conversation entity which has two one-to-many relationships with a User entity: 
conversation<<->user
conversation<<->coach
Both "user" and "coach" are of User type.

**Comment by dorada** [comment]
Is this still an issue with the current master?

**Comment by sigmundfridge** [comment]
@dorada: we work on the same database so you'll be able to answer that one for me.

**Comment by dorada** [comment]
Then we'll assume I have this under control!
