### ISSUE TITLE
nodeCache creates [NSManagedObject isTemporaryID] unrecognized selector exception

### ISSUE THREAD

**Issue by jasper-ch-chan** [project-imas/encrypted-core-data#174]
The situation is as follows. I am currently using concurrency in my app and I have two persisting mocs, each directly connected to the psc. I have a private moc and a main moc. Whenever the private moc saves the information to the psc, I will add an observer to observe NSManagedObjectContextDidSaveNotification. When that occurs, I will get the main thread to merge between the two contexts. 

When I use the stock SQLite class, it merges fine but when I turn ECD back on, I notice that the main moc gets some temporary objects. Has anyone else experienced this? 

EDIT: The exact error I get is
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ChunkHeader isTemporaryID]: unrecognized selector sent to instance 0x786e88b0'
```

I purposely chose not to use nested contexts.

Thanks in advanced!

**Comment by jasper-ch-chan** [comment]
I found a past issue in ECD that has been closed, and with its solution of commenting out the cache hit portion, the issue is gone. 

 ```Cache fails to update when updating an NSManagedObject for a value that was fetched form the database as Nil #118 ```

**Comment by jasper-ch-chan** [comment]
UPDATE:

This problem seems to be affecting my relationship. I can still access all of the attributes of the NSManagedObject when I use po, but I get the following exception when I try to po the relationship object

```
error: Execution was interrupted, reason: breakpoint 1.1.
The process has been returned to the state before expression evaluation.
```

**Comment by jasper-ch-chan** [comment]
UPDATE:

@gavin-black I removed the merging portion and had the objects inserted/updated via the main moc and the issue went away. Any helpful suggestions as to where to go from here?

**Comment by AndrewMcDrew** [comment]
Hi, I have a very similar problem, isTemporaryID as an unrecognized selector. It really affects one-to-many relationship. In the method
```Objective-C 
- (BOOL)handleUpdatedObjectsInSaveRequest:(NSSaveChangesRequest *)request cache:(NSMutableDictionary *)cache error:(NSError **)error
```
 code adds a changed managed property to the cache like
```Objective-C 
[cacheChanges setObject:value forKey:obj];.
```
But if the managed property(value) is a relationship then this adds an object instead of objectID, that is required due to the NSIncrementalStoreNode documentation. I think this is why later the unrecognized selector crash appears, because Core Date requires NSManagedObjecID, not an object itself. Fixed it like
```Objective-C
if ([property isKindOfClass:[NSRelationshipDescription class]]) {
    [cacheChanges setObject:[value objectID] forKey:obj];
} else {
    [cacheChanges setObject:value forKey:obj];
}
```

**Comment by jasper-ch-chan** [comment]
@AndrewMcDrew Thank you very much for your solution. I did try it and it does seem to solve the problem!

@gavin-black @zerpt Are there any concerns with this solution? If not, @AndrewMcDrew if you could kindly put in a pull request so this solution can be merged in, that would be awesome!
