### ISSUE TITLE
Has anyone tried modifying options for ECD (namely NSPersistentStoreFileProtectionKey)?

### ISSUE THREAD

**Issue by jasper-ch-chan** [project-imas/encrypted-core-data#183]
So I'm currently experimenting with the options NSDictionary being passed into ECD and I'm noticing that it doesn't seem to respond as expected. I tried changing my code base to use default NSSQLite and it worked fine. 

Has anyone experimented with the options? Is NSPersistentStoreFileProtectionKey supported in ECD? If not, does anyone know where I should start looking to support this?

**Comment by sahara108** [comment]
Yes I did, if you enable data protection and leave this key empty, encrypted core data will use "NSFileProtectionComplete" (or NSFileProtectionCompleteUnlessOpen, I haven't check that). In my case, I change it to NSFileProtectionCompleteUntilFirstUserAuthentication by giving option like that: 
NSDictionary *options = @{
                              EncryptedStorePassphraseKey : key,
                              NSInferMappingModelAutomaticallyOption : @YES,
                              NSMigratePersistentStoresAutomaticallyOption : @(YES),
                              NSPersistentStoreFileProtectionKey  : NSFileProtectionCompleteUntilFirstUserAuthentication
                              };

Note: if you are working on existed db, you need to do this as well:
NSDictionary *fileAttributes = [NSDictionary dictionaryWithObject:NSFileProtectionCompleteUntilFirstUserAuthentication forKey:NSFileProtectionKey];
[[NSFileManager defaultManager] setAttributes:fileAttributes ofItemAtPath:path error:&error];
for the data base file

**Comment by jasper-ch-chan** [comment]
@sahara108 You're a life saver mate. Cheers!
