### ISSUE TITLE
DB Merge Issue

### ISSUE THREAD

**Issue by Sasoman** [project-imas/encrypted-core-data#186]
Hi Gregg, Gavin

My company and I have been using your project to help encrypt our DB to which it has been
working great.

We ran into an issue where we needed to migrate. This seems to be an issue
reported before.
https://github.com/project-imas/encrypted-core-data/issues/14

The app has since gone live and we simply can not delete the app and start
over.

I was wondering if you help us to just decrypt the database. if you could
help provide some sample code, it would be great.

I will be happy to pay for your consulting fees to help us resolve this
issue quickly.

Again, we just need to decrypt the DB and we will do the migration manually. Or unless you have a better solution.

Either way, i'm look forward to your response!

Thanks,
Taso

**Comment by jasper-ch-chan** [comment]
@Sasoman 
Hey Taso,

I'm sorry to hear that you are running into problems with migration. Would you be able to kindly describe what sort of problems you're experiencing? In the meanwhile, I currently use SQLiteManager (http://www.sqlabs.com/sqlitemanager.php) to help decrypt my database files. You will need the encryption key though.

**Comment by Sasoman** [comment]
Yes, I used SQLiteManager and was able to open the DB with the security code. No problem there.
We have since changed the model of our db and is having trouble migrating.

It is failing with error message.
Missing old model, cannot migrate database

NSDictionary *options = @{ EncryptedStorePassphraseKey: securityKey,
EncryptedStoreDatabaseLocation: storeURL,
NSSQLitePragmasOption: @{@"journal_mode": @"DELETE"},
NSMigratePersistentStoresAutomaticallyOption: @YES,
NSInferMappingModelAutomaticallyOption: @YES};
//[EncryptedStore makeStoreWithOptions:options managedObjectModel:[self managedObjectModel]];
NSPersistentStoreCoordinator *coordinator = [EncryptedStore makeStoreWithOptions:options
managedObjectModel:[self managedObjectModel]];

**Comment by jasper-ch-chan** [comment]
@Sasoman Curiously, are you migrating between model versions that are directly consecutive to each other? (IE. version 1 to version 2) Or are you jumping versions? (IE. version 1 to version 3)

Strictly based the error message alone, isn't the compiler struggling to locate your old data model? Did you make any changes to your old data model, causing the hash value to be different thus unable to recognize it?

**Comment by Sasoman** [comment]
We are migrating from consecutive versions.We have not made any changes to old data model

**Comment by jasper-ch-chan** [comment]
@Sasoman This is probably obvious, but you have tried stepping through the sorting process of the data model? A good place to start would be:  

''' 
- (BOOL)migrateFromModel:(NSManagedObjectModel *)fromModel toModel:(NSManagedObjectModel *)toModel error:(NSError **)error
'''

I bring this up because based on your error alone, I don't believe it is failing the migration process. It seems to fail prior to even executing any migration. Short of you giving me your source code, I am currently unsure what other sort of helpful comments I could provide.

**Comment by Sasoman** [comment]
How can send you source code/project?

**Comment by jasper-ch-chan** [comment]
@Sasoman 
Personally, I would prefer you try to debug it yourself so not only will you learn more about ECD and quite frankly, I am not convinced I will be able to allocate much time to your code in the next few months.

**Comment by Sasoman** [comment]
Totally understand.  Do you have any sample code on how we can decrypt the DB?  I downloaded the tool you recommended and I was able to open it with the tool so i know that works.  But how would i go about removing the encryption from the code side?  Do you have sample code?

**Comment by jasper-ch-chan** [comment]
@Sasoman I've read on other issues that some people have written code such that you would basically open up the encrypted database, and insert all the records into another database that is NOT encrypted. That is one way I suppose. Aside from that, I am unsure of another way presently.

**Comment by jasper-ch-chan** [comment]
@Sasoman 
Any updates on this issue?

**Comment by shabeerali** [comment]
I have the problem that  I cannot perform a light weight migration. I have added one attribute in one of the entity and when migrates, all existing values in that entity set to nil. Why?

**Comment by PradeshKumar-emisweb** [comment]
@shabeerali - Have you found the solution? @jasper-ch-chan - Still progressive migration isn't possible with ECD?

**Comment by shabeerali** [comment]
I got my problem solved.  Thanks for replaying to my email.  Thanks...

**Comment by PradeshKumar-emisweb** [comment]
@shabeerali - Even, we have the same issue, can you plz help out how you have sort out this issue?
