### ISSUE TITLE
Cannot migrate entity table with indexed columns

### ISSUE THREAD

**Issue by cicciotti-privatewave** [project-imas/encrypted-core-data#187]
When migrating a table to a new version of the data model, Encrypted Core Data renames the existing table to free up the name for the new version of the table. It doesn't, however, rename the indexes for its columns, which makes the creation of the new table fail

**Comment by ppaulojr** [comment]
+1 here.

**Comment by dorada** [comment]
Is this still an issue with master? I think it now drops and recreates the indexes

**Comment by ppaulojr** [comment]
Sorry I didn't answer. I think it's working okay now. At least in the project I have,
