### ISSUE TITLE
Migration from plain(unencrypted) DB to encrypted DB

### ISSUE THREAD

**Issue by praveenrajnatarajan** [project-imas/encrypted-core-data#189]
is there a option for  migrating plain to encrypted in sql cipher.

**Comment by zhuxi1989** [comment]
Try this method in NSPersistentCoordinator
migratePersistentStore: toURL: options: withType: error:

**Comment by praveenrajnatarajan** [comment]
The Encrypted store creates a new table, with some change in column name from the meta data of the existing plain table and replaces the existing sqlite file.

**Comment by gavin-black** [comment]
Hi @praveenrajnatarajan,

Just curious if the method @zhuxi1989 mentioned worked?  I think this is essentially supported, just not entirely convenient.

Thanks,

-- Gavin

**Comment by aleufms** [comment]
Can you post an exemple of code to do this?

Thank you.
