### ISSUE TITLE
[QUESTION] How to change kasword on existing database

### ISSUE THREAD

**Issue by Michal1313** [project-imas/encrypted-core-data#196]
Hi,

At first big thanks for you work. You are doing great job, it is awesome!

I have noticed that you are added option to change password on existing, already encrypted database.

I have created NSPersistentStore like so:

    NSPersistentStoreCoordinator *coordinator = [EncryptedStore makeStore:[self managedObjectModel] passcode:@"SOME_PASSWORD"];

In EncryptedStore class I noticed such method:

    - (BOOL)changeDatabasePassphrase:(NSString *)passphrase error:(NSError *__autoreleasing*)error;

Can you tell me please how should I use it with already created NSPersistentStoreCoordinator?

**Comment by sahara108** [comment]
Hi,
I managed to change the database password. You can pull it from my master: https://github.com/sahara108/encrypted-core-data. But I got another problem that the database with new password can't be saved.
Because we are in beta now, so it is not urgent thing to fix. But I must fix it as soon as possible. Could you try it and collaborate with me to fix it. 
Thanks

**Comment by lolgear** [comment]
Hi! 
I looked into my project and noticed that this method can't be used directly. Well, this method doesn't make sense as a complete action.
Your first step should be 'unlock' database and later you should change the password of your database.

As a solution try to use another method with several parameters as old and new passphrases.
It should open database with old passphrase and set new passphrase.

Sorry, I can't provide it here in case of IPad usage and not stable internet connection.

**Comment by lolgear** [comment]
I talk about this method in previous comment:
`- (BOOL)changeDatabasePassphrase:(NSString *)oldPassphrase toNewPassphrase:(NSString *)newPassphrase error:(NSError *__autoreleasing*)error;`
