### ISSUE TITLE
could not prepare statement: ambiguous column name: ecdParentObject.createdAt

### ISSUE THREAD

**Issue by dorada** [project-imas/encrypted-core-data#213]
My Data Model has several related entities which are all have the same parent object, this seems to be confusing ECD as it tries to join the same table multiple times:

    2015-12-16 15:13:36.073 A[35373:16612356] SQL DEBUG: SELECT ecdParentObject.createdAt, ............, ecdParentObject.customer__objectid, ecdParentObject.__entityType, ecdParentObject.user__objectid, ecdParentObject.__entityType FROM ecdParentObject 
    INNER JOIN ecdParentObject ON ecdParentObject.__objectid=ecdParentObject.customer__objectid OR ecdParentObject.customer__objectid IS NULL 
    INNER JOIN ecdParentObject ON ecdParentObject.__objectid=ecdParentObject.user__objectid OR ecdParentObject.user__objectid IS NULL WHERE ecdParentObject.__objectid=?;
    2015-12-16 15:13:36.073 A[35373:16612356] could not prepare statement: ambiguous column name: ecdParentObject.createdAt

I have a potential fix using an hash alias, it appears to work: 

    - (NSIncrementalStoreNode *)newValuesForObjectWithID:(NSManagedObjectID *)objectID
                                         withContext:(NSManagedObjectContext *)context
                                               error:(NSError **)error {
    ...
                    NSString *destinationTable = [self tableNameForEntity:destinationEntity];
                    NSString *destinationAlias = [NSString stringWithFormat:@"T%lul",(unsigned long)destinationEntity.hash];
                  
                  
                    // Add teh type column to the query
                    NSString *typeColumn = [NSString stringWithFormat:@"%@.__entityType", destinationAlias];
                    [columns addObject:typeColumn];
                    
                    // Create the join
                    NSString *join = [NSString stringWithFormat:@" INNER JOIN %@ as %@ ON %@.__objectid=%@.%@", destinationTable, destinationAlias,destinationAlias, table, column];

=== after

    SELECT ecdParentObject.createdAt, ...., ecdParentObject.customer__objectid, T10786525947237944154l.__entityType, ecdParentObject.user__objectid, T5859180595705617885l.__entityType FROM ecdParentObject 
    INNER JOIN ecdParentObject as T10786525947237944154l ON T10786525947237944154l.__objectid=ecdParentObject.customer__objectid OR ecdParentObject.customer__objectid IS NULL 
    INNER JOIN ecdParentObject as T5859180595705617885l ON T5859180595705617885l.__objectid=ecdParentObject.user__objectid OR ecdParentObject.user__objectid IS NULL WHERE ecdParentObject.__objectid=?;

Is this an acceptable way to fix this? I'm happy so submit the change.

Daniel.

**Comment by nfox513** [comment]
Daniel, I have a pull request submitted that should fix your issue. I'm not sure why it hasn't been merged in yet.

https://github.com/project-imas/encrypted-core-data/pull/210

**Comment by dorada** [comment]
nfox513 - you seem to be bypassing the joins for relationships with the same parent table - is that the right course of action?

**Comment by nfox513** [comment]
SQL is pretty far from my core competencies, but it doesn't really make sense to join a table onto itself, does it? If there's another, more acceptable solution (or if there's some issue with mine) I'm all for it. Looks like aliasing the table as in your solution would work, but I'm not sure if joining the same table twice via an alias has any performance impact vs not joining it at all.

**Comment by nfox513** [comment]
Actually I just ran into an issue with my implementation that your aliasing solves, revolving around ambiguous columns, but this time in the SELECT statement, not the JOIN. I'll close my pull request and submit a new one with your change (or you can submit it, if you'd like). I also have another issue I am submitting a pull request for, so I can lump them together.

**Comment by nfox513** [comment]
Just to follow up, I've submitted a new pull request utilizing your alias fix, as well as another bug I ran into: https://github.com/project-imas/encrypted-core-data/pull/214

**Comment by dorada** [comment]
Great!

I have some code coming to allow lightweight migrations to work with Parent Entities. I think that will then give complete support for entity hierarchies.

**Comment by dorada** [comment]
This issue is now resolved
