### ISSUE TITLE
Implicit declaration of function 'sqlite3_key' is invalid in C99

### ISSUE THREAD

**Issue by dvi** [project-imas/encrypted-core-data#282]
Hi, 
I trying to build my project on Xcode 9 beta I am getting the following two errors.

Implicit declaration of function 'sqlite3_key' is invalid in C99
Implicit declaration of function 'sqlite3_rekey' is invalid in C99

podfile:

inhibit_all_warnings!
use_frameworks!

target 'MyApp' do
    pod 'EncryptedCoreData', :git => 'https://github.com/project-imas/encrypted-core-data.git' 
end

Any thoughts?

**Comment by jcavar** [comment]
Should be solved by https://github.com/project-imas/encrypted-core-data/pull/283

**Comment by dvi** [comment]
tnx!
