### ISSUE TITLE
Cannot compile using Xcode 9

### ISSUE THREAD

**Issue by namalu** [project-imas/encrypted-core-data#287]
Errors when building Incremental Store Demo using Xcode 9:

- EncryptedStore.m Line 1162 'Implicit declaration of function `sqlite3_rekey' is invalid in C99`
- EncryptedStore.m Line 1185 'Implicit declaration of function `sqlite3_key' is invalid in C99`

**Comment by lolgear** [comment]
@namalu 
Headers collision.
iOS 11 has header in usr/include sqlite3.h

**Comment by kirthika** [comment]
Any workaround?

**Comment by lolgear** [comment]
@kirthika I installed everything by cocoa pods.
I caught error in case of forked repository.
So, I merged master of this repo into master of my repo.
And everything works fine now.
