### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by jcavar** [project-imas/encrypted-core-data#308]
Hello everyone,

I would like to understand the status of this project. There is very low activity, quite a lot of issues and PRs.
Latest release was more then a year ago.

Is this project deprecated, or is temporary problem with time? Do you still plan to maintain it?

**Comment by gavin-black** [comment]
Unfortunately we are no longer actively maintaining the project.  I'd hoped Apple would address the issue themselves at some point (We've talked with them about it briefly before).  Definitely wouldn't mind having others act as a maintainer if there is interest though.
