### ISSUE TITLE
NSPredicate error

### ISSUE THREAD

**Issue by tsvijayan** [project-imas/encrypted-core-data#46]
Using the following NSPredicate code is failing when encrypted core data is used , but works fine when normal core data is used
@"sessionJobStatus == '%@' OR sessionJobStatus == '%@' OR sessionJobStatus == '%@'"

for example " sessionJobStatus == "2004" OR sessionJobStatus == "2002" OR sessionJobStatus == "2001"

Looks like predicate parsing function "- (NSDictionary *)whereClauseWithFetchRequest:(NSFetchRequest *)request" is not proper

The result of whereClauseWithFetchRequest is as follows
(sessionJobStatus = ? OR sessionJobStatus = ? OR sessionJobStatus = ?)

Regards,
Vijayan

**Comment by sandeepmagantimobisoft** [comment]
else {
query = [@[leftOperand, [operator objectForKey:@"operator"], rightOperand] componentsJoinedByString:@" "];
} 

Getting error at this part of the code.
