### ISSUE TITLE
Cannot fetch with predicate referencing a managed object

### ISSUE THREAD

**Issue by patrickhartling** [project-imas/encrypted-core-data#51]
I put together a [test case](https://gist.github.com/patrickhartling/8482725) that demonstrates trying to fetch using a predicate that references another managed object. If the store type is `EncryptedStoreType`, the fetch fails with this error:

```
Error Domain=NSSQLiteErrorDomain Code=1 "The operation couldn’t be completed. (NSSQLiteErrorDomain error 1.)" UserInfo=0x2c2d8a0 {EncryptedStoreErrorMessage=near "<": syntax error}
```

The test code uses a managed object has a temporary ID, but it fails in the same way if the object has a permanent ID.

The test behaves correctly if the store type is `NSSQLiteStoreType`.

**Comment by salils1337** [comment]
I'm using NSExpression and NSExpressionDescription for calculating sums for multiple fields.
I get the following error -

**Error Domain=NSSQLiteErrorDomain Code=1 "The operation couldn’t be completed. (NSSQLiteErrorDomain error 1.)" UserInfo=0x7fb2ce5e8dd0 {EncryptedStoreErrorMessage=near "FROM": syntax error}**

If I remove the encrypted-core-data store setup code and revert back to the default Apple one it runs fine. 
Any help appreciated as I need SQLCipher for encryption over core data and this library is the only way I can.

**Comment by dorada** [comment]
sum() queries are now supported
