### ISSUE TITLE
Migration and Transformer issues

### ISSUE THREAD

**Issue by gavin-black** [project-imas/encrypted-core-data#56]
The EncryptedCoreDataTests still have several errors that need addressed:

Right now I see:

```EncryptedCoreDataTests.m: error: testCustomTransformer (EncryptedCoreDataTests) failed: 'Test object <float=72379128682929452842713677299712.000000, uint64=7162247752875012965' should be equal to 'Test object <float=3.141593, uint64=18446744073709551614' The two ECDTestObject instances should be equal```

```EncryptedCoreDataTests.m: error: testDefaultTransformer (EncryptedCoreDataTests) failed: '<62706c69 73743030 d4010203 0405080b 0c542474 6f705824 6f626a65 63747358 24766572 73696f6e 59246172 63686976 6572d106 0754726f 6f748001 a2090a55 246e756c 6c4b6563 64737562 54797065 73120001 86a05f10 0f4e534b 65796564 41726368 69766572 0811161f 2832353a 3c3f4551 56000000 00000001 01000000 00000000 0d000000 00000000 00000000 00000000 68>' should be equal to '(```

```EncryptedCoreDataTests.m: error: testMigration (EncryptedCoreDataTests) failed: "migrated" should be true. Failed to migrate to the new managed object model: Error Domain=NSCocoaErrorDomain Code=1570 "The operation couldn’t be completed. (Cocoa error 1570.)" UserInfo=0x1115c8b0 {NSValidationErrorObject=<NSManagedObject: 0x23782a0> (entity: Transaction; id: 0xc65bdb0 <x-coredata://106FCF63-3745-4B59-BD26-7CAC94A7DBBE/Transaction/p1> ; data: <fault>), NSValidationErrorKey=account, NSLocalizedDescription=The operation couldn’t be completed. (Cocoa error 1570.)}```

```error: testFetchObjectWithTemporaryID (EncryptedCoreDataTests) failed: Cannot retrieve referenceObject from an objectID that was not created by this store```

This last error seems to be tied to the newly added unique column names.  Not sure why it only appears on the migration testing, could pop up other places as well.

**Comment by sedwo** [comment]
+1
We too are concerned about going further with this wonderful class due to its lack of progressive migration support.
Curiously then, any further update on this?

**Comment by dorada** [comment]
Migration support has moved forward considerably since this discussion, please raise any bug reports as a new issue
