### ISSUE TITLE
All queries expressions without rightBindings have their operators turned to "IS" 

### ISSUE THREAD

**Issue by tslater** [project-imas/encrypted-core-data#95]
What is the purpose of this line?
``` if([[operator objectForKey:@"operator"] isEqualToString:@"!="]) {```
Inside recursiveWhereClauseWithFetchRequest?

I have a predicate like this: ```dirtyTime != Nil && (syncedTime == Nil || dirtyTime >= syncedTime)``` and the query ends up being:
 ````SELECT ecdAddress.__objectID FROM ecdAddress  WHERE (ecdAddress.dirtyTime IS NOT NULL AND (ecdAddress.syncedTime IS NULL OR ecdAddress.dirtyTime IS ecdAddress.syncedTime));````

I traced it back to that line but don't want to break things. If you someone lets me know what functionality to preserve with the whole ```IS``` bit I'll submit a PR.

BTW, great work with this! It's so awesome. Totally saving my butt.

**Comment by ThePragmaticArt** [comment]
@DanielBroad it would seem there are other issues with this logic as well. Especially when you create an NSExpression with a constantValue. This seems to evaluate into a comparison going to a "?".  The "rightBindings" value doesn't seem to properly populate the query if the value exists as a constant value.

Example:

```
SELECT ecdObject.__objectID FROM ecdObject  WHERE ecdObject.id = ? LIMIT 1;
```

where the binding has 1 element being the constant value of the expression:

```
NSExpression(forConstantValue: "\(identifier)")
```

```
let keyPathExpression = NSFetchRequestExpression(forKeyPath: identifierKeyPath)
let identifierExpression = expression(for: identifier)
        
let predicate = NSComparisonPredicate(leftExpression: keyPathExpression, rightExpression: identifierExpression, modifier: .direct, type: .equalTo, options: [])
```

```
        // build result and return
        if (rightOperand && !rightBindings) {
            if([[operator objectForKey:@"operator"] isEqualToString:@"!="]) {
                query = [@[leftOperand, @"IS NOT", rightOperand] componentsJoinedByString:@" "];
            } else {
                query = [@[leftOperand, @"IS", rightOperand] componentsJoinedByString:@" "];
            }
        } else if (([rightOperand isEqualToString:@"?"] || !rightOperand) && rightBindings) { //This check is missing
            query = [@[leftOperand, [operator objectForKey:@"operator"], rightBindings] componentsJoinedByString:@" "];
            if ([[operator objectForKey:@"operator"] isEqualToString:@"LIKE"]) {
                query = [query stringByAppendingString:@" ESCAPE '\\'"];
            }
        } else {
            query = [@[leftOperand, [operator objectForKey:@"operator"], rightOperand] componentsJoinedByString:@" "];
            if ([[operator objectForKey:@"operator"] isEqualToString:@"LIKE"]) {
                query = [query stringByAppendingString:@" ESCAPE '\\'"];
            }
        }
```
