### ISSUE TITLE
Exact comparison ("=") in NSPredicate is not working, only LIKE

### ISSUE THREAD

**Issue by rzolin** [project-imas/encrypted-core-data#97]
I am initializing the store with my model that I am getting from an SDK bundle (not by merging bundles as in the examples). But it works with regular CoreData:
```
NSPersistentStoreCoordinator *coordinator = [EncryptedStore makeStore:self.model passcode:@"SOME_PASSWORD"];
```
And then simple predicates like this do not work:
```
    NSFetchRequest *request = [[NSFetchRequest alloc] initWithEntityName:@"ATUser"];
    NSPredicate *predicate = [NSPredicate predicateWithFormat:@"userID == %@", profileID];
    [request setPredicate:predicate];
    NSManagedObjectContext *context = [NSManagedObjectContext MR_contextForCurrentThread];
    NSError *error = nil;
    NSArray *users = [context executeFetchRequest:request error:&error];
    if (!users) return nil;
    if (error) { NSLog(@"%@", error); }
    return users[0];
```

Though if I replace `@"userID == %@"` with `@"userID LIKE %@"` it works. But this is not an exact match and may/will not work for everything.

The userID is a simple string field, no special treatments. Tried with lastName and similar fields (not IDs) - the same behavior.

There is additional weirdness. I couldn't properly initialize the existing store with:
```
- (NSPersistentStoreCoordinator *) encryptedPersistentStoreCoordinatorWithModel:(NSManagedObjectModel *) model at:(NSString *)dbPath
{
    NSPersistentStoreCoordinator *coordinator = nil;

    // get the coordinator
    coordinator = [[NSPersistentStoreCoordinator alloc] initWithManagedObjectModel:model];

    // add store
    NSError *error = nil;
    NSURL *databaseURL = [NSURL fileURLWithPath:dbPath];

    // I am reusing the file, not deleting it every time. 
//    [[NSFileManager defaultManager] removeItemAtURL:databaseURL error:&error];

    NSDictionary *options = @{
            EncryptedStorePassphraseKey : @"DB_KEY_HERE",
            NSMigratePersistentStoresAutomaticallyOption : @YES,
            NSInferMappingModelAutomaticallyOption : @YES
    };
    NSPersistentStore *store = [coordinator
            addPersistentStoreWithType:EncryptedStoreType
                         configuration:nil
                                   URL:databaseURL
                               options:options
                                 error:&error];
    NSAssert(store, @"Unable to add persistent store!\n%@", error);

    return coordinator;
}
```
The code above creates the store (exact match still doesn't work), but on restart of the app, the store is not created (the ivar `store` is empty and there are no errors). Though I need to create the store in a specific file and directory.

Any help would be greatly appreciated! Thanks.

**Comment by jasper-chan** [comment]
Hello Zerpt,
Is there any updates on this issue? 

If anyone else is currently experiencing this problem, I'm currently doing a work around by using stringWithFormat to force it to be evaluated as a NSString.

**Comment by zhuxi1989** [comment]
meet the same issue and looks like the latest commit on #97 does not fix it.

**Comment by revathi-ram** [comment]
What is the work around to the above problem? Kindly update.
